## Deliverable 2. Create a Customer Travel Destinations Map.

In [1]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps
import matplotlib.pyplot as plt
import numpy as np
# Import API key
from config import g_key
from config import weather_api_key

In [2]:
# 1. Import the WeatherPy_database.csv file. 
city_data_df = pd.read_csv("C:\\Users\\manri\\Desktop\\Master Class\\Module 6\\World_Weather_Analysis\\Weather_Database\\WeatherPy_database.csv")

In [3]:
# 2. Prompt the user to enter minimum and maximum temperature criteria 
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))

What is the minimum temperature you would like for your trip? 65
What is the maximum temperature you would like for your trip? 90

In [4]:
# 3. Filter the city_data_df DataFrame using the input statements to create a new DataFrame using the loc method.
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                       (city_data_df["Max Temp"] >= min_temp)]
preferred_cities_df.tail()
preferred_cities_df.head()

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
0,0,Rikitea,PF,-23.1203,-134.9692,79.00,72,1,17.92,light rain
1,1,Arraial Do Cabo,BR,-22.9661,-42.0278,78.80,83,0,11.50,clear sky
3,3,Port Lincoln,AU,-34.7333,135.8667,65.08,59,33,9.66,scattered clouds
4,4,Harper,LR,4.3750,-7.7169,78.30,90,1,7.07,clear sky
5,5,Atuona,PF,-9.8000,-139.0333,80.92,75,27,19.30,scattered clouds

In [5]:
# 4a. Determine if there are any empty rows.
preferred_cities_df.count()

City_ID                311
City                   311
Country                308
Lat                    311
Lng                    311
Max Temp               311
Humidity               311
Cloudiness             311
Wind Speed             311
Current Description    311
dtype: int64

In [6]:
# 4b. Drop any empty rows and create a new DataFrame that doesnâ€™t have empty rows.
clean_df = preferred_cities_df.dropna()

In [7]:
# 5a. Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = clean_df[["City", "Country", "Max Temp", "Current Description", "Lat", "Lng"]].copy()

# 5b. Create a new column "Hotel Name"
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,Rikitea,PF,79.00,light rain,-23.1203,-134.9692,
1,Arraial Do Cabo,BR,78.80,clear sky,-22.9661,-42.0278,
3,Port Lincoln,AU,65.08,scattered clouds,-34.7333,135.8667,
4,Harper,LR,78.30,clear sky,4.3750,-7.7169,
5,Atuona,PF,80.92,scattered clouds,-9.8000,-139.0333,
6,Cayenne,GF,81.00,scattered clouds,4.9333,-52.3333,
7,Pouebo,NC,84.63,few clouds,-20.4000,164.5667,
10,Nueva Loja,EC,86.00,scattered clouds,0.0847,-76.8828,
12,Meulaboh,ID,76.14,overcast clouds,4.1363,96.1285,
16,Butaritari,KI,81.77,scattered clouds,3.0707,172.7902,

In [8]:
# 6a. Set parameters to search for hotels with 5000 meters.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

# 6b. Iterate through the hotel DataFrame.
for index, row in hotel_df.iterrows():
    
# 6c. Get latitude and longitude from DataFrame
    lat = row["Lat"]
    lng = row["Lng"]

    # Add the latitude and longitude to location key for the params dictionary.
    params["location"] = f"{lat},{lng}"

    # 6d. Set up the base URL for the Google Directions API to get JSON data.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    
    # 6e. Make request and retrieve the JSON data from the search. 
    hotels = requests.get(base_url, params=params).json()
    
    # 6f. Get the first hotel from the results and store the name, if a hotel isn't found skip the city.
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    except (IndexError):
        print("Hotel not found... skipping.")
        
#Recall that when trying to parse the data from an API request, we need to use a try-except block to handle the error with 
#a statement and continue the retrieval.

hotel_df.head(10)

Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,Rikitea,PF,79.00,light rain,-23.1203,-134.9692,Pension Maro'i
1,Arraial Do Cabo,BR,78.80,clear sky,-22.9661,-42.0278,Pousada Porto Praia
3,Port Lincoln,AU,65.08,scattered clouds,-34.7333,135.8667,Port Lincoln Hotel
4,Harper,LR,78.30,clear sky,4.3750,-7.7169,Screensaver
5,Atuona,PF,80.92,scattered clouds,-9.8000,-139.0333,Villa Enata
6,Cayenne,GF,81.00,scattered clouds,4.9333,-52.3333,HÃ´tel Le Dronmi
7,Pouebo,NC,84.63,few clouds,-20.4000,164.5667,
10,Nueva Loja,EC,86.00,scattered clouds,0.0847,-76.8828,Limoncocha Great Hotel
12,Meulaboh,ID,76.14,overcast clouds,4.1363,96.1285,Kost Pria
16,Butaritari,KI,81.77,scattered clouds,3.0707,172.7902,Isles Sunset Lodge

In [9]:
# 7. Drop the rows where there is no Hotel Name.
hotel_df.replace("", np.nan, inplace=True)
hotel_df.dropna(subset=["Hotel Name"], inplace=True)
hotel_df.head()

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,Rikitea,PF,79.00,light rain,-23.1203,-134.9692,Pension Maro'i
1,Arraial Do Cabo,BR,78.80,clear sky,-22.9661,-42.0278,Pousada Porto Praia
3,Port Lincoln,AU,65.08,scattered clouds,-34.7333,135.8667,Port Lincoln Hotel
4,Harper,LR,78.30,clear sky,4.3750,-7.7169,Screensaver
5,Atuona,PF,80.92,scattered clouds,-9.8000,-139.0333,Villa Enata

In [10]:
# 8a. Create the output File (CSV)
output_data_file = "C:\\Users\\manri\\Desktop\\Master Class\\Module 6\\World_Weather_Analysis\\Vacation_Search\\WeatherPy_vacation.csv"

# 8b. Export the City_Data into a csv
hotel_df.to_csv(output_data_file, index_label="City_ID")

In [11]:
# 9. Using the template add city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Description</dt><dd>{Current Description}</dd>
<dt>Max Temp</dt><dd>{Max Temp} Â°F</dd>
</dl>
"""

# 10a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = hotel_df[["Lat", "Lng"]]

In [13]:
# 11a. Add a marker layer for each city to the map. 
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,dissipating=False,
             max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)

# 11b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))